name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - name: Build and Test
      run: xcodebuild test -scheme TestApp1 -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      run: xcodebuild test -scheme TestApp1 -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'