name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: Build and Test
      run: xcodebuild test -scheme TestApp1 -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'